spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${RDS_HOST}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

oauth2:
  kakao:
    user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
    id-token-info: https://kauth.kakao.com/oauth/tokeninfo
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json
    app-key: ${KAKAO_APP_KEY}
  apple:
    public-key-url: https://appleid.apple.com/auth/keys

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: a